version: "3"

services:
  mongo:
    image: mongo:4.4
    container_name: easy_db
    restart: always
    ports: 
      - 2701:2701
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
  mongo-express:
    image: mongo-express
    container_name: easy_express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
  backend:
    container_name: easy_backend
    depends_on:
      - "mongo"
    restart: always
    build: .
    command: npm start
    ports:
      - "3000:3000"
    external_links:
      - db
    volumes:
      - ".:/usr/app"
