version: "3"

services:
  app:
    container_name: easy_backend
    restart: always
    build: .
    depends_on: 
      - mongo
    command: npm start 
    ports:
      - '3333:3333'
    volumes:
      - .:/usr/app
    external_links:
      - easy_db
  mongo:
    image: mongo
    container_name: easy_db
    restart: always
    ports:
      - '8017:8017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  mongo-express:
    image: mongo-express
    container_name: express
    restart: always
    depends_on: 
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
 