version: '3'

services:
  db:
    image: mongo:4.2
    container_name: db
    ports: 
      - '27017:27017' 
  backend:
    container_name: backend
    restart: always
    build: .
    command: npm start
    ports: 
      - '3000:3000'
    external_links: 
      - db
    volumes: 
      - '.:/usr/app'
  